// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANb3UFFwV3QR4-PYlMlsF-qpRQyC4ahkg',
    appId: '1:711223055888:web:880b65eec3b84e2c9d9c95',
    messagingSenderId: '711223055888',
    projectId: 'tenant-bureau',
    authDomain: 'tenant-bureau.firebaseapp.com',
    storageBucket: 'tenant-bureau.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFOEu-aTdBjA2zt-a9-1-sFikwEC2y7k',
    appId: '1:711223055888:android:39862f0a612fa03c9d9c95',
    messagingSenderId: '711223055888',
    projectId: 'tenant-bureau',
    storageBucket: 'tenant-bureau.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL1a854qHJXBTfmq4UHFNhmg55Cb5J1SY',
    appId: '1:711223055888:ios:48db209e4a333bd89d9c95',
    messagingSenderId: '711223055888',
    projectId: 'tenant-bureau',
    storageBucket: 'tenant-bureau.appspot.com',
    androidClientId: '711223055888-gost2c4sdq92l760nnmit7k1ameamn69.apps.googleusercontent.com',
    iosClientId: '711223055888-n31u1dj0q2qv31ar9vju7ill3os0qqdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tenantBureau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL1a854qHJXBTfmq4UHFNhmg55Cb5J1SY',
    appId: '1:711223055888:ios:48db209e4a333bd89d9c95',
    messagingSenderId: '711223055888',
    projectId: 'tenant-bureau',
    storageBucket: 'tenant-bureau.appspot.com',
    androidClientId: '711223055888-gost2c4sdq92l760nnmit7k1ameamn69.apps.googleusercontent.com',
    iosClientId: '711223055888-n31u1dj0q2qv31ar9vju7ill3os0qqdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tenantBureau',
  );
}
